Fix compilation issues
- missing autoconf define
```
ERROR: /home/aeh/proj/ocp-diag-sat/src/BUILD:48:10: Compiling src/main.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 150 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from src/adler32memcpy.h:12,
                 from src/os.h:22,
                 from src/finelock_queue.h:19,
                 from src/sat.h:20,
                 from src/main.cc:10:
src/sattypes.h: In function 'const char* Timestamp()':
src/sattypes.h:41:41: error: 'STRESSAPPTEST_TIMESTAMP' was not declared in this scope; did you mean 'STRESSAPPTEST_SAT_H_'?
   41 | inline const char *Timestamp() { return STRESSAPPTEST_TIMESTAMP; }
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~
      |                                         STRESSAPPTEST_SAT_H_
```

- array-bounds warn -> error
```
INFO: From Compiling src/google/protobuf/repeated_field.cc:
In file included from /usr/include/string.h:535,
                 from external/com_google_protobuf/src/google/protobuf/stubs/port.h:39,
                 from external/com_google_protobuf/src/google/protobuf/stubs/logging.h:35,
                 from external/com_google_protobuf/src/google/protobuf/repeated_field.h:55,
                 from external/com_google_protobuf/src/google/protobuf/repeated_field.cc:35:
In function 'void* memcpy(void*, const void*, size_t)',
    inlined from 'void google::protobuf::internal::ElementCopier<Element, true>::operator()(Element*, const Element*, int) [with Element = bool]' at external/com_google_protobuf/src/google/protobuf/repeated_field.h:1011:11,
    inlined from 'void google::protobuf::RepeatedField< <template-parameter-1-1> >::CopyArray(Element*, const Element*, int) [with Element = bool]' at external/com_google_protobuf/src/google/protobuf/repeated_field.h:996:37,
    inlined from 'void google::protobuf::RepeatedField< <template-parameter-1-1> >::MoveArray(Element*, Element*, int) [with Element = bool]' at external/com_google_protobuf/src/google/protobuf/repeated_field.h:990:12,
    inlined from 'void google::protobuf::RepeatedField< <template-parameter-1-1> >::Reserve(int) [with Element = bool]' at external/com_google_protobuf/src/google/protobuf/repeated_field.h:971:14,
    inlined from 'google::protobuf::RepeatedField< <template-parameter-1-1> >::RepeatedField(const google::protobuf::RepeatedField< <template-parameter-1-1> >&) [with Element = bool]' at external/com_google_protobuf/src/google/protobuf/repeated_field.h:532:12:
/usr/include/bits/string_fortified.h:29:33: warning: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' offset 0 is out of the bounds [0, 0] [-Warray-bounds]
[...]
ERROR: /home/aeh/.cache/bazel/_bazel_aeh/9375093f9ce015fb2a02a2b446a58bf6/external/boringssl/BUILD:161:11: Compiling src/crypto/x509v3/v3_utl.c failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 37 arguments skipped)
```

- maybe-uninitialized warn -> error
```
INFO: From Compiling src/core/ext/xds/xds_endpoint.cc:
In file included from /usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/vector:64,
                 from external/com_github_grpc_grpc/src/core/ext/xds/xds_endpoint.h:29,
                 from external/com_github_grpc_grpc/src/core/ext/xds/xds_endpoint.cc:19:
In member function 'std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = grpc_core::XdsEndpointResource::Priority; _Alloc = std::allocator<grpc_core::XdsEndpointResource::Priority>]',
    inlined from 'grpc_error_handle grpc_core::{anonymous}::EdsResourceParse(const grpc_core::XdsEncodingContext&, const envoy_config_endpoint_v3_ClusterLoadAssignment*, bool, grpc_core::XdsEndpointResource*)' at external/com_github_grpc_grpc/src/core/ext/xds/xds_endpoint.cc:301:57,
    inlined from 'virtual absl::StatusOr<grpc_core::XdsResourceType::DecodeResult> grpc_core::XdsEndpointResourceType::Decode(const grpc_core::XdsEncodingContext&, absl::string_view, bool) const' at external/com_github_grpc_grpc/src/core/ext/xds/xds_endpoint.cc:361:74:
/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_vector.h:1124:41: warning: 'priority' may be used uninitialized [-Wmaybe-uninitialized]
 1124 |         return *(this->_M_impl._M_start + __n);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
external/com_github_grpc_grpc/src/core/ext/xds/xds_endpoint.cc: In member function 'virtual absl::StatusOr<grpc_core::XdsResourceType::DecodeResult> grpc_core::XdsEndpointResourceType::Decode(const grpc_core::XdsEncodingContext&, absl::string_view, bool) const':
external/com_github_grpc_grpc/src/core/ext/xds/xds_endpoint.cc:287:12: note: 'priority' was declared here
  287 |     size_t priority;
      |            ^~~~~~~~
ERROR: /home/aeh/.cache/bazel/_bazel_aeh/9375093f9ce015fb2a02a2b446a58bf6/external/boringssl/BUILD:161:11: Compiling src/crypto/x509v3/v3_utl.c failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 37 arguments skipped)
```

Signed-off-by: mimir-d <mimir-d@users.noreply.github.com>